# Site settings
title: BioJS Workshop
email: 
description: "Presented by BioJS 2.0"
baseurl: ""
url: "http://ebi.biojs.net/"
github: "biojs/biojs-ebi"
twitter_username: 
github_username:  

analytics :
  provider : google
  google :
      tracking_id : ''

plugins: ./_plugins

# Build settings
markdown: kramdown
kramdown:
   input: GFM

permalink: pretty
