# Site settings
title: Protein Prediction 2
email: 
description: "Protein Prediction at Technical University of Munich"
baseurl: "/biojs-lab"
url: "http://daviddao.github.io/"
twitter_username: 
github_username:  

analytics :
  provider : google
  google :
      tracking_id : ''

plugins: ./_plugins

# Build settings
markdown: kramdown
kramdown:
   input: GFM

permalink: pretty
